version: "3.8"

services:
  postgres:
    image: postgres:16.7
    container_name: postgres_16_7
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskmanagement
      POSTGRES_PASSWORD: Salo1234.
      POSTGRES_DB: taskdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

