services:
  postgres:
    image: postgres:16.7
    container_name: postgres_16_7
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskmanagement
      POSTGRES_PASSWORD: Salo1234.
      POSTGRES_DB: taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
